
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.fullname" . }}-gui
  labels:
    app: {{ template "spark.name" . }}
    chart: {{ template "spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.master.ui_port }}
      name: gui
  selector:
    app: {{ template "spark.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "spark.fullname" . }}
  labels:
    app: {{ template "spark.name" . }}
    chart: {{ template "spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "spark.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "spark.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "spark.name" . }}
        chart: {{ template "spark.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ template "spark.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        ports:
        - containerPort: {{ .Values.master.port }}
        - containerPort: {{ .Values.master.ui_port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- range $key, $value := .Values.master.customEnv }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        args:
        - standalone
        - master
        - --port {{ .Values.master.port }}
        - --webui-port {{ .Values.master.ui_port }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
