apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-testing.fullname" . }}-logging
  labels:
    app: {{ include "platform-testing.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  logging.conf: |-
{{ tpl (.Files.Get "resources/config/logging.conf") . | indent 4 }}
