apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-cp-kafka-jmx
  labels:
    app: {{ template "platform-testing.name" . }}
    chart: {{ template "platform-testing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 5555
      name: jmx
  selector:
    app: "cp-kafka"
    release: {{ .Release.Name }}
