### General PNDA Values
serviceAccountName: pnda
roleName: pnda-role
roleBindingName: pnda

hbase:
  enable: true
hdfs:
  enabled: true
  # The base hadoop image to use for all components.
  # See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
  image:
    repository: gradiant/hadoop-base
    tag: 2.7.7
    pullPolicy: IfNotPresent
  # The version of the hadoop libraries being used in the image.
  hadoopVersion: 2.7.7
  conf:
    hdfs-site:
      #hdfs property needed if hbase is deploy with hdfs
      dfs.datanode.max.transfer.threads: 4096

grafana:
  enable: true
  sidecar:
    datasources:
      enabled: true
      # label that the configmaps with datasources are marked with
      label: grafana_datasource

## ------------------------------------------------------
## Jupyterhub
## ------------------------------------------------------
jupyterhub:
  enabled: true
  hub:
    uid: 0
    fsGid: 0
    image:
      name: pnda/k8s-hub
      tag: '0.8.2'
    extraConfig:  
      00-custom-singleuser-hostname: |
         c.KubeSpawner.extra_pod_config = {
            "hostname": "jupyter-{username}",
            "subdomain": "hub-subdomain"
         }
  singleuser:
    serviceAccountName: pnda
    image:
      # Check https://github.com/Gradiant/dockerized-jupyter/blob/master/Dockerfile
      name: gradiant/jupyter
      tag: 5.7.8
    extraEnv:
      SPARKCONF_SPARK_MASTER: "spark://spark-standalone:7077"
  ingress:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m

## ------------------------------------------------------
## Confluent Platform
## ------------------------------------------------------
# To enable/disable cp services
cp-schema-registry:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-ksql-server:
  enabled: false
cp-zookeeper:
  enabled: true
cp-kafka:
  enabled: true
# Since cp-platform define all cp-services as subcharts we have to configure
# them with the parent chart name as root
# (we set 'confluent-platform' as an alias name in requirements.yaml)
confluent-platform:
  cp-zookeeper:
    persistence:
      enabled: true
  cp-kafka:
    image: confluentinc/cp-kafka
    imageTag: 5.0.1
    persistence:
      enable: true
kafka-manager:
  enabled: true
  image:
    repository: gradiant/kafka-manager
    tag: 2.0.0.2
    pullPolicy: Always
  clusters:
   - name: "PNDA-Kafka"
     #It will default to the Kafka-manager zookeeper hosts if not specified
     # zkHosts: ""
     kafkaVersion: "2.0.0"
     jmxEnabled: "true"
     tuning: {}

## ------------------------------------------------------
## Spark standalone
## ------------------------------------------------------
spark-standalone:
  enabled: false

platform-testing:
  enabled: true

redis:
  enabled: true
  usePassword: false

console-frontend:
  ingress:
    enabled: true
    hosts:
      - console.pnda.io
