# Default values for platform-testing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: testing

schedule: "* * * * *"

image:
  repository: pnda/platform-testing
  tag: latest-py3
  pullPolicy: IfNotPresent

conf:
  logLevel: WARNING

resources:
  requests:
    memory: "128Mi"
    cpu: "10m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
