{{- if .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ include "hbase.fullname" . }}-master-env
  namespace: {{ .Release.Namespace }}
  selfLink: /api/v1/namespaces/{{ .Release.Namespace }}/configmaps/{{ include "hbase.fullname" . }}-master-env
data:
  hbase-env.sh: |-
    HBASE_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
    export HBASE_MASTER_OPTS="$HBASE_JMX_OPTS -Dcom.sun.management.jmxremote.port=5555"
  jmxremote.passwd: |-
    monitorRole monitorpass
    controlRole controlpass
  jmxremote.access: |-
    monitorRole readonly
    controlRole readwrite
  hadoop-metrics.properties: |-
    hbase.class=org.apache.hadoop.metrics.spi.NullContextWithUpdateThread
    hbase.period=10
    jvm.class=org.apache.hadoop.metrics.spi.NullContextWithUpdateThread
    jvm.period=10
    rpc.class=org.apache.hadoop.metrics.spi.NullContextWithUpdateThread
    rpc.period=10
{{- end }}