apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}-master
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: master
spec:
  serviceName: {{ include "hbase.fullname" . }}-master
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "hbase.name" . }}
        release: {{ .Release.Name }}
        component: master
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hbase.name" . }}
                release: {{ .Release.Name | quote }}
                component: master
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hbase.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: master
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - "/bin/bash"
        - "/tmp/hbase-config/bootstrap.sh"
        - "-d"
        resources:
{{ toYaml .Values.hbase.master.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config
      volumes:
      - name: hbase-config
        configMap:
          name: {{ .Release.Name }}-hbase
