apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}-master
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: master
spec:
  serviceName: {{ include "hbase.fullname" . }}-master
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "hbase.name" . }}
        release: {{ .Release.Name }}
        component: master
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hbase.name" . }}
                release: {{ .Release.Name | quote }}
                component: master
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hbase.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: master
        {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      {{- if .Values.prometheus.jmx.enabled }}
      - name: master-jmx-exporter
        image: "{{ .Values.prometheus.jmx.image }}:{{ .Values.prometheus.jmx.imageTag }}"
        command:
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -XX:MaxRAMFraction=1
        - -XshowSettings:vm
        - -jar
        - jmx_prometheus_httpserver.jar
        - {{ .Values.prometheus.jmx.port | quote }}
        - /etc/jmx-hbase/hbase_jmx_config.yaml
        ports:
        - containerPort: {{ .Values.prometheus.jmx.port }}
        resources:
{{ toYaml .Values.prometheus.jmx.resources | indent 10 }}
        volumeMounts:
        - name: pnda-hbase-exporter-javaagent
          mountPath: /etc/jmx-hbase/hbase_jmx_config.yaml
          subPath: hbase_jmx_config.yaml       
      {{- end }}
      - name: master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - "/bin/bash"
        - "/tmp/hbase-config/bootstrap.sh"
        - "-d"
        resources:
{{ toYaml .Values.hbase.master.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config
        {{- if .Values.prometheus.jmx.enabled }}
        - name: pnda-hbase-master-env
          mountPath: /opt/hbase-2.0.1/conf
        {{- end }}
      volumes:
      - name: hbase-config
        configMap:
          name: {{ .Release.Name }}-hbase
      {{- if .Values.prometheus.jmx.enabled }}
      - name: pnda-hbase-exporter-javaagent
        configMap:
          name: {{ .Release.Name }}-hbase-exporter-javaagent
      - name: pnda-hbase-master-env
        configMap:
          name: {{ .Release.Name }}-hbase-master-env
      {{- end }}