{{- if .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
  name: {{ include "hbase.fullname" . }}-exporter-javaagent
  namespace: {{ .Release.Namespace }}
  selfLink: /api/v1/namespaces/{{ .Release.Namespace }}/configmaps/{{ include "hbase.fullname" . }}-exporter-javaagent
data:
  hbase_jmx_config.yaml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
{{- end }}