{{- if index .Values "confluent-platform" "cp-kafka" "prometheus" "jmx" "enabled"}}
kind: Service
apiVersion: v1
metadata:
  name: kafka-metric
  labels:
    monitoring: prometheus
spec: 
  selector: 
    app: cp-kafka
  ports:
  - port: {{ index .Values "confluent-platform" "cp-kafka" "prometheus" "jmx" "port" }}
    name: metrics
    targetPort: {{ index .Values "confluent-platform" "cp-kafka" "prometheus" "jmx" "port" }}
{{- end }}
