{
 "title": "PNDA dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance_node_exporter",
    "query": "label_values(node_boot_time_seconds{job=\"node-exporter\"}, instance)"
   },
   {
    "name": "instance_hdfs",
    "query": "label_values(jvm_memory_bytes_init{job=\"pnda-hdfs-namenode-metric\"}, instance)"
   },
   {
    "name": "instance_hbase_master",
    "query": "label_values(hadoop_hbase_logerror{job=\"pnda-hbase-master-metric\"}, instance)"
   },
   {
    "name": "instance_hbase_region",
    "query": "label_values(hadoop_hbase_logerror{job=\"pnda-hbase-region-metric\"}, instance)"
   },
   {
    "name": "instance_spark",
    "query": "label_values(jvm_pools_Code_Cache_committed{job=\"spark-standalone-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"$instance_node_exporter\"}[2m]))) * 100\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance_node_exporter\",job=~\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance_node_exporter\",job=~\"node-exporter\"} )) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance_node_exporter\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_filesystem_usage:\n", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"$instance_node_exporter\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (irate(node_cpu_seconds_total{mode!=\"idle\", instance=\"$instance_node_exporter\"}[5m])) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "HDFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_init{area=\"heap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}\n",
       "legendFormat": "initial heap"
      },
      {
       "expr": "jvm_memory_bytes_max{area=\"heap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}",
       "legendFormat": "max heap"
      },
      {
       "expr": "jvm_memory_bytes_committed{area=\"heap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}",
       "legendFormat": "committed heap"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}",
       "legendFormat": "used heap"
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_init{area=\"nonheap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}\n",
       "legendFormat": "initial nonheap"
      },
      {
       "expr": "jvm_memory_bytes_max{area=\"nonheap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}",
       "legendFormat": "max nonheap"
      },
      {
       "expr": "jvm_memory_bytes_committed{area=\"nonheap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}",
       "legendFormat": "committed nonheap"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"nonheap\",endpoint=\"metrics\",instance=\"$instance_hdfs\"}",
       "legendFormat": "used nonheap"
      }
     ]
    },
    {
     "title": "Code Cache Pool Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Code Cache\"}",
       "legendFormat": "initial"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Code Cache\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Code Cache\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Code Cache\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Metaspace Pool Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Metaspace\"}",
       "legendFormat": "initial"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Metaspace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Metaspace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Metaspace\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Compressed Class Space Pool Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Compressed Class Space\"}",
       "legendFormat": "initial"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Compressed Class Space\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Compressed Class Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"Compressed Class Space\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Eden Space Pool Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Eden Space\"}",
       "legendFormat": "initial"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Eden Space\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Eden Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Eden Space\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Survivor Space Pool Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Survivor Space\"}",
       "legendFormat": "initial"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Survivor Space\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Survivor Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Survivor Space\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Old Gen Pool Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Old Gen\"}",
       "legendFormat": "initial"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Old Gen\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Old Gen\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",instance=\"$instance_hdfs\",pool=\"G1 Old Gen\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "HBase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Process Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_processcpuload{endpoint=\"metrics\",instance=\"$instance_hbase_master\"}\n",
       "legendFormat": "master process"
      },
      {
       "expr": "java_lang_operatingsystem_processcpuload{endpoint=\"metrics\",instance=\"$instance_hbase_region\"}",
       "legendFormat": "region process"
      }
     ]
    },
    {
     "title": "CPU System Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_systemcpuload{endpoint=\"metrics\",instance=\"$instance_hbase_master\",job=\"pnda-hbase-master-metric\"}",
       "legendFormat": "master system"
      },
      {
       "expr": "java_lang_operatingsystem_systemcpuload{endpoint=\"metrics\",instance=\"$instance_hbase_region\",job=\"pnda-hbase-region-metric\"}",
       "legendFormat": "region system"
      }
     ]
    },
    {
     "title": "CPU Current Thread Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_threading_currentthreadcputime{endpoint=\"metrics\",instance=\"$instance_hbase_master\"}",
       "legendFormat": "master thread"
      },
      {
       "expr": "java_lang_threading_currentthreadcputime{endpoint=\"metrics\",instance=\"$instance_hbase_region\"}",
       "legendFormat": "region thread"
      }
     ]
    },
    {
     "title": "Total Info Logs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(hadoop_hbase_loginfo)\n" }
     ]
    },
    {
     "title": "Total Warnings Logs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(hadoop_hbase_logwarn)" }
     ]
    },
    {
     "title": "Total Error Logs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sum(hadoop_hbase_logerror)" }
     ]
    },
    {
     "title": "Total Fatal Logs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(hadoop_hbase_logfatal)" }
     ]
    },
    {
     "title": "Memory Pool CodeCache MASTER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_master\",job=\"pnda-hbase-master-metric\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\",service=\"pnda-hbase-master-metric\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_master\",job=\"pnda-hbase-master-metric\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\",service=\"pnda-hbase-master-metric\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_master\",job=\"pnda-hbase-master-metric\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\",service=\"pnda-hbase-master-metric\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_master\",job=\"pnda-hbase-master-metric\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\",service=\"pnda-hbase-master-metric\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool CodeCache REGION",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Code Cache\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Code Cache\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Code Cache\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Code Cache\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool Metaspace MASTER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"Metaspace\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"Metaspace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"Metaspace\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"Metaspace\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool Metaspace REGION",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Metaspace\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Metaspace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Metaspace\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"Metaspace\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool OldGen MASTER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Old Gen\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Old Gen\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Old Gen\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Old Gen\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool OldGen REGION",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Old Gen\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Old Gen\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Old Gen\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Old Gen\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool EdenSpace MASTER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Eden Space\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Eden Space\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_master\",name=\"PS Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool EdenSpace REGION",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Eden Space\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Eden Space\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",instance=\"$instance_hbase_region\",name=\"PS Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_heap_init{endpoint=\"metrics\",instance=\"$instance_spark\"}\n",
       "legendFormat": "initial heap"
      },
      {
       "expr": "jvm_heap_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "max heap"
      },
      {
       "expr": "jvm_heap_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "committed heap"
      },
      {
       "expr": "jvm_heap_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "used heap"
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_non_heap_init{endpoint=\"metrics\",instance=\"$instance_spark\"}\n",
       "legendFormat": "initial heap"
      },
      {
       "expr": "jvm_non_heap_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "max heap"
      },
      {
       "expr": "jvm_non_heap_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "committed heap"
      },
      {
       "expr": "jvm_non_heap_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "used heap"
      }
     ]
    },
    {
     "title": "Memory Pool CodeCache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_pools_Code_Cache_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_pools_Code_Cache_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_pools_Code_Cache_init{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "jvm_pools_Code_Cache_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool EdenSpace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_pools_Eden_Space_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_pools_Eden_Space_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_pools_Eden_Space_init{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "jvm_pools_Eden_Space_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool Metaspace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_pools_Metaspace_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_pools_Metaspace_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_pools_Metaspace_init{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "jvm_pools_Metaspace_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool SurvivorSpace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_pools_Survivor_Space_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_pools_Survivor_Space_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_pools_Survivor_Space_init{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "jvm_pools_Survivor_Space_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Pool TenuredGen",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_pools_Tenured_Gen_committed{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_pools_Tenured_Gen_used{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_pools_Tenured_Gen_init{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Init"
      },
      {
       "expr": "jvm_pools_Tenured_Gen_max{endpoint=\"metrics\",instance=\"$instance_spark\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Total Workers",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 47 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(master_workers)\n" }
     ]
    },
    {
     "title": "Total Alive Workers",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 47 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(master_aliveWorkers)\n" }
     ]
    },
    {
     "title": "Total Apps",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 51 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(master_apps)\n" }
     ]
    },
    {
     "title": "Total Waiting Apps",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 51 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(master_waitingApps)\n" }
     ]
    }
   ]
  }
 ]
}