{{- if .Values.ingress.nameNode.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hdfs.fullname" . }}-namenode
  labels:
    app: {{ include "hdfs.name" . }}
    chart: {{ include "hdfs.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.ingress.nameNode.labels }}
{{ toYaml .Values.ingress.nameNode.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.nameNode.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.nameNode.host }}
      http:
        paths:
          - path: {{ .Values.ingress.nameNode.path | quote }}
            backend:
              serviceName: {{ include "hdfs.fullname" . }}-namenode
              servicePort: 50070
{{- end }}