{{- if .Values.ingress.dataNode.enabled -}}
{{- $fullName := include "hdfs.fullname" . -}}
{{- $ingressPath := .Values.ingress.dataNode.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-datanode
  labels:
    app: {{ include "hdfs.name" . }}
    chart: {{ include "hdfs.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.ingress.dataNode.labels }}
{{ toYaml .Values.ingress.dataNode.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.dataNode.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec: 
  rules:
    - host: {{ .Values.ingress.dataNode.host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ include "hdfs.fullname" . }}-datanode
              servicePort: 50075
{{- end }}